spring:
  #静态资源处理
#  web:
#    resources:
#      #启动默认静态资源处理，默认true
#      add-mappings: true
#      cache:
#        cachecontrol:
#          #缓存响应时间，单位是秒
#          max-age:3600
#      chain:
#        #资源链启用缓存，默认启动true
#        cache: true
#        #启用资源链，默认禁用false
#        enabled: true
#        #压缩资源（gzip,brotli），默认禁用
#        compressed: true
#      static-locations: classpath:/static/
#

  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache : false
    #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&servserTimezone=Asia/Shanghai
    username: root
    password: Ling
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间 默认600000
      idle-timeout: 1800000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间 0表示永久存活，默认1800000
      max-lifetime: 1800000
      #连接超时时间 默认30000
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

#redis配置
  redis:
  #服务器地址
    host: localhost
  #端口
    port: 6379
  #默认数据库
    database: 0
    #连接超市时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 0
    password: Liang


#rabbitmq配置
  rabbitmq:
    #服务器
    host: localhost
    #用户名密码
    username: Liang
    password: Liang
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次处理一条消息，处理完再继续处理下一条消息
        prefetch: 1
        #启动时是否启动容器，默认为true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数,默认3
        max-attempts: 3
        #重试最大间隔时间，10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1







# mybatis-puls 配置
mybatis-plus:
  # 配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型别名（默认类名）
  type-aliases-package: com.example.seckilldemo


# Mybatis SQL打印（方法接口所在的包，不是mybatis.xml所在的包）
logging:
  level:
#    ROOT: WARN
    com.example.seckilldemo.mapper: DEBUG
  file:
    name: target/app.log